config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'

  get     '/search',  to: 'static_pages#search'
  get     '/posts',   to: 'static_pages#result'

  get     '/notifications', to: 'notifications#index'
  get     '/stream',  to: 'static_pages#stream'

  resources :users, param: :user_name do
    member do
      get :following, :followers
    end
  end
  resources :likes, only: [:index, :create, :destroy]
  resources :posts, only: [:show, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @post = current_user.posts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def stream
    @post = Post.all.paginate(page: params[:page])
  end

  def search
    @q = current_user.feed.ransack(params[:q])
  end

  def result
    if  params[:q][:content_cont].blank?
      @feed_items = []
    else
      @q = current_user.feed.ransack(params[:q])
      @feed_items = @q.result.paginate(page: params[:page])
    end
  end

end

app/views/static_pages/home.html.erb
<% if logged_in? %>

  <%= render 'shared/stats' %>

  <%= render 'shared/post_form' %>

  <% if @feed_items.any? %>
    <ul class="posts">
      <% @feed_items.each do |post| %>
        <%= render 'posts/post_with_parent', post: post %>
      <% end %>
    </ul>
    <%= will_paginate @feed_items %>
  <% end %>

<% else %>

  <div class="row">
    <div class="col-md-4 col-md-offset-4">

    <%= form_for(:session, url: login_path) do |f| %>
      <%= f.text_field :user_name, class: "form-control", placeholder: "ユーザ名" %>

      <%= f.password_field :password, class: "form-control", placeholder: "パスワード" %>

      <%= f.label :remember_me, class: "checkbox" do %>
        <%= f.check_box :remember_me %> 保存する
      <% end %>

      <%= f.submit "ログイン", class: "btn btn-info" %>
    <% end %>

    <%= link_to "アカウント作成", signup_path, class: "btn btn-info", style: "width: 100%; margin-top: 30px;" %>

  </div>
</div>

<% end %>

app/views/static_pages/result.html.erb
<h2>検索 / <%= @feed_items.count %>件</h2>

<ul class="posts">
  <%= render @feed_items %>
</ul>

app/views/static_pages/search.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">検索</div>
  </div>
  <div class="panel-body">
    <%= search_form_for(@q, method: :get) do |f| %>
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="form-group">
            <%= f.text_field :content_cont, class: "form-control", placeholder: "部分一致" %>
          <div>
      </div>
      <%= f.submit '検索', class: "btn btn-primary" %>
    <% end %>
  <div>
</div>

app/views/static_pages/stream.html.erb
<h2>ストリーム</h2>

<% if @post.any? %>
  <ul class="posts">
    <% @post.each do |post| %>
      <%= render 'posts/post_with_parent', post: post %>
    <% end %>
  </ul>
  <%= will_paginate @post %>
<% end %>