config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'

  get     '/search',  to: 'static_pages#search'
  get     '/posts',   to: 'static_pages#result'

  get     '/notifications', to: 'notifications#index'
  get     '/stream',  to: 'static_pages#stream'

  resources :users, param: :user_name do
    member do
      get :following, :followers
    end
  end
  resources :likes, only: [:index, :create, :destroy]
  resources :posts, only: [:show, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="error_explanation">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<div class="post_form">
  <%= form_for @post, html: { multipart: true } do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, class: "form-control", placeholder: "わーい、たーのしー！" %>
    </div>
    <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
    <%= hidden_field_tag :post_id, params[:id] %>
    <%= f.submit "つぶやく", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="profile">

  <div class="profile_icon">
    <span><%= link_to user_icon, @user %></span>
    <span><%= render 'users/follow_btn', user: @user if logged_in? %></span>
  </div>

  <div class="profile_wrapper">
    <div class="profile_header">
      <span><%= link_to user_name, @user %></span>
    </div>

    <div>
      <span><%= @user.posts.count %> ツイート</span>
      <span><%= link_to following_user_path(@user) do %><%= @user.following.count %> フォロー<% end %></span>
      <span><%= link_to followers_user_path(@user) do %><%= @user.followers.count %> フォロワー<% end %></span>
    </div>

    <div class="profile_body">
      <span><%= @user.profile %></span>
    </div>
  </div>

</div>