config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'

  get     '/search',  to: 'static_pages#search'
  get     '/posts',   to: 'static_pages#result'

  get     '/notifications', to: 'notifications#index'
  get     '/stream',  to: 'static_pages#stream'

  resources :users, param: :user_name do
    member do
      get :following, :followers
    end
  end
  resources :likes, only: [:index, :create, :destroy]
  resources :posts, only: [:show, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes

  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 1000 }
  validate  :picture_size

  has_ancestry

  private

    def picture_size
      if picture.size > 1.megabytes
        errors.add(:picture, "should be less than 1MB")
      end
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def show
    @post = current_user.posts.build
    @root = Post.find_by(id: params[:id])
  end

  def create
    root = Post.find_by(id: params[:post_id])
    if !root.nil?
      send_params = post_params
      send_params.store(:user_id, current_user.id)
      @post = root.children.build(send_params)
    else
      @post = current_user.posts.build(post_params)
    end

    if @post.save
      redirect_to request.referrer || root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end

  end

  def destroy
    @post.destroy
    flash[:success] = "削除されました！"
    redirect_to request.referrer || root_url
  end

  private

    def post_params
      params.require(:post).permit(:content, :picture)
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>" class="post_wrapper">
  <div><%= post.id %></div>
  <div class="post_icon"><%= link_to user_icon(post.user), post.user %></div>
  <div class="post_body">
    <div class="post_header">
      <span class="user"><%= link_to user_name(post.user), post.user %></span>
      <span class="timestamp"><%= time_ago_in_words(post.created_at) %>前</span>
      <span>
        <% if current_user.likes.flat_map {|i| i[:post_id] }.include?(post.id) %>
          <%= link_to content_tag(:i, '', class: 'glyphicon glyphicon-heart'), like_path(post), method: :delete %>
        <% else %>
          <%= link_to content_tag(:i, '', class: 'glyphicon glyphicon-heart-empty'), likes_path(post_id: post.id), method: :post %>
        <% end %>
      </span>
      <span>
        <% if current_user?(post.user) %>
          <%= link_to content_tag(:i, '', class: 'glyphicon glyphicon-trash'), post, method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
      </span>
    </div>
    <div class="post_content">
      <span class="content">
        <%= link_to simple_format(h(post.content)), post_path(post) %>
        </span>
      <span><%= image_tag post.picture.url if post.picture? %></span>
    </div>
  </div>
  <div class="post_count"><%= post.children.count %> POSTS</div>
</li>

app/views/posts/_post_with_parent.html.erb
<li id="post-<%= post.id %>" class="post_wrapper">
  <div><%= post.id %></div>
  <div class="post_icon"><%= link_to user_icon(post.user), post.user %></div>
  <div class="post_body">
    <div class="post_header">
      <span class="user"><%= link_to user_name(post.user), post.user %></span>
      <span class="timestamp"><%= time_ago_in_words(post.created_at) %>前</span>
      <span>
        <% if current_user.likes.flat_map {|i| i[:post_id] }.include?(post.id) %>
          <%= link_to content_tag(:i, '', class: 'glyphicon glyphicon-heart'), like_path(post), method: :delete %>
        <% else %>
          <%= link_to content_tag(:i, '', class: 'glyphicon glyphicon-heart-empty'), likes_path(post_id: post.id), method: :post %>
        <% end %>
      </span>
      <span>
        <% if current_user?(post.user) %>
          <%= link_to content_tag(:i, '', class: 'glyphicon glyphicon-trash'), post, method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
      </span>
    </div>
    <div class="post_content">
      <span class="content">
        <%= link_to simple_format(h(post.content)), post_path(post) %>
        </span>
      <span><%= image_tag post.picture.url if post.picture? %></span>
    </div>
  </div>
  <div class="post_count"><%= post.children.count %> POSTS</div>

  <% if !post.parent.nil? %>
    <% post = post.parent %>
    <div> >> </div>

    <div><%= post.id %></div>
      <div class="post_icon"><%= link_to user_icon(post.user), post.user %></div>
      <div class="post_body">
        <div class="post_header">
          <span class="user"><%= link_to user_name(post.user), post.user %></span>
          <span class="timestamp"><%= time_ago_in_words(post.created_at) %>前</span>
          <span>
            <% if current_user.likes.flat_map {|i| i[:post_id] }.include?(post.id) %>
              <%= link_to content_tag(:i, '', class: 'glyphicon glyphicon-heart'), like_path(post), method: :delete %>
            <% else %>
              <%= link_to content_tag(:i, '', class: 'glyphicon glyphicon-heart-empty'), likes_path(post_id: post.id), method: :post %>
            <% end %>
          </span>
          <span>
            <% if current_user?(post.user) %>
              <%= link_to content_tag(:i, '', class: 'glyphicon glyphicon-trash'), post, method: :delete, data: { confirm: "You sure?" } %>
            <% end %>
          </span>
        </div>
        <div class="post_content">
          <span class="content">
            <%= link_to simple_format(h(post.content)), post_path(post) %>
            </span>
          <span><%= image_tag post.picture.url if post.picture? %></span>
        </div>
      </div>
      <div class="post_count"><%= post.children.count %> POSTS</div>
  <% end %>

</li>

app/views/posts/show.html.erb
<ul class="posts">
  <% @root.ancestors.each do |ancestor| %>
    <%= render 'post', post: ancestor %>
  <% end %>
  <%= render 'post', post: @root %>
</ul>

<%= render 'shared/post_form', post: @root %>


<% if @root.has_children? %>
  <ul class="posts">
    <% @root.children.reorder(id: :asc).each do |child| %>
      <%= render 'posts/post', post: child %>
    <% end %>
  </ul>
<% end %>