config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'

  get     '/search',  to: 'static_pages#search'
  get     '/posts',   to: 'static_pages#result'

  get     '/notifications', to: 'notifications#index'
  get     '/stream',  to: 'static_pages#stream'

  resources :users, param: :user_name do
    member do
      get :following, :followers
    end
  end
  resources :likes, only: [:index, :create, :destroy]
  resources :posts, only: [:show, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <% if logged_in? %>
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "通知", notifications_path %></li>
        <li><%= link_to "いいね", likes_path %></li>
        <li><%= link_to "ユーザ", users_path %></li>
        <li><%= link_to "設定", edit_user_path(current_user) %></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li><%= link_to current_user.user_name, current_user %></li>
        <li><%= link_to 'ストリーム', stream_path %></li>
        <li><%= link_to "検索", search_path %></li>
        <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
      <% end %>
    </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title><%= title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <%= render 'layouts/header' %>

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>

    </div>
  </body>

</html>